language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t karolinak1904/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true karolinak1904/react-test npm test

after_success:
    - docker build -t karolinak1904/multi-client ./client
    - docker build -t karolinak1904/multi-nginx ./nginx
    - docker build -t karolinak1904/multi-server ./server
    - docker build -t karolinak1904/multi-worker ./worker
    # Log in to the docker CLI 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push karolinak1904/multi-client
    - docker push karolinak1904/multi-nginx
    - docker push karolinak1904/multi-server
    - docker push karolinak1904/multi-worker
